# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/2019_FPGA_Design/Lab02/Lab2-1/Lab2-1_prj/Lab2-1_prj.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_1/design_1_RGB_LED_0_1.xci
# IP: The module: 'design_1_RGB_LED_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2019_FPGA_Design/Lab02/Lab2-1/Lab2-1_prj/Lab2-1_prj.srcs/2019_FPGA_Design/Lab02/Lab2-1/RGB_LED/RGB_LED.srcs/constrs_1/new/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: d:/2019_FPGA_Design/Lab02/Lab2-1/Lab2-1_prj/Lab2-1_prj.srcs/sources_1/bd/design_1/ip/design_1_RGB_LED_0_1/design_1_RGB_LED_0_1.xci
# IP: The module: 'design_1_RGB_LED_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/2019_FPGA_Design/Lab02/Lab2-1/Lab2-1_prj/Lab2-1_prj.srcs/2019_FPGA_Design/Lab02/Lab2-1/RGB_LED/RGB_LED.srcs/constrs_1/new/RGB_LED_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_RGB_LED_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
