# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Desktop/pynq-z2_v1.0.xdc

# Block Designs: bd/design_1/design_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_PWM_Decoder_0_1/design_1_PWM_Decoder_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_PWM_Decoder_0_1 || ORIG_REF_NAME==design_1_PWM_Decoder_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_RGB_LED_0_1/design_1_RGB_LED_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_1_RGB_LED_0_1 || ORIG_REF_NAME==design_1_RGB_LED_0_1} -quiet] -quiet

# XDC: bd/design_1/design_1_ooc.xdc
